title: BanzhanBaicha's Homepage
page-top-title: BanzhanBaicha
top-section-bg-text: Be what you wanna be
home-subtitle: Yourname&ensp;|&ensp;BanzhanBaicha
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
